local M = {}

M.icons = {
	Class = " ",
	Color = " ",
	Constant = " ",
	Constructor = " ",
	Enum = "了 ",
	EnumMember = " ",
	Field = " ",
	File = " ",
	Folder = " ",
	Function = " ",
	Interface = "ﰮ ",
	Keyword = " ",
	Method = "ƒ ",
	Module = " ",
	Property = " ",
	Snippet = "﬌ ",
	Struct = " ",
	Text = " ",
	Unit = " ",
	Value = " ",
	Variable = " ",
}

M.signs = {
	Error = " ",
	Warn = " ",
	Hint = " ",
	Info = " ",
}

vim.g.use_nerd_icons = false

M.kind = {
	Text = " ",
	Method = " ",
	Function = " ",
	Constructor = " ",
	Field = " ",
	Variable = " ",
	Class = " ",
	Interface = " ",
	Module = " ",
	Property = " ",
	Unit = " ",
	Value = " ",
	Enum = " ",
	Keyword = " ",
	Snippet = " ",
	Color = " ",
	File = " ",
	Reference = " ",
	Folder = " ",
	EnumMember = " ",
	Constant = " ",
	Struct = " ",
	Event = " ",
	Operator = " ",
	TypeParameter = " ",
	Misc = " ",
}
M.type = {
	Array = " ",
	Number = " ",
	String = " ",
	Boolean = " ",
	Object = " ",
}
M.documents = {
	File = " ",
	Files = " ",
	Folder = " ",
	OpenFolder = " ",
}
M.git = {
	Add = " ",
	Mod = " ",
	Remove = " ",
	Ignore = " ",
	Rename = " ",
	Diff = " ",
	Repo = " ",
	Octoface = " ",
}
M.ui = {
	ArrowClosed = "",
	ArrowOpen = "",
	Lock = " ",
	Circle = " ",
	BigCircle = " ",
	BigUnfilledCircle = " ",
	Close = " ",
	NewFile = " ",
	Search = " ",
	Lightbulb = " ",
	Project = " ",
	Dashboard = " ",
	History = " ",
	Comment = " ",
	Bug = " ",
	Code = " ",
	Telescope = " ",
	Gear = " ",
	Package = " ",
	List = " ",
	SignIn = " ",
	SignOut = " ",
	NoteBook = " ",
	Check = " ",
	Fire = " ",
	Note = " ",
	BookMark = " ",
	Pencil = " ",
	ChevronRight = "",
	Table = " ",
	Calendar = " ",
	CloudDownload = " ",
}
M.diagnostics = {
	Error = " ",
	Warning = " ",
	Information = " ",
	Question = " ",
	Hint = " ",
}
M.misc = {
	Robot = " ",
	Squirrel = " ",
	Tag = " ",
	Watch = " ",
	Smiley = " ",
	Package = " ",
}

return M
